

spring:
  datasource:
    url: jdbc:mysql://umc-rds.cnvgwr3tpow8.ap-northeast-2.rds.amazonaws.com/practice?useUnicode=true&serverTimezone=Asia/Seoul&useSSL=false
    username: admin
    password: 12341234
#  live reloading ? ?? ?? ??
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false





#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/itemservice?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#
#spring.datasource.username=root
#spring.datasource.password=12345678
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
